// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9tddkILb_kfB_1urYIM6bCFU8h9yMd38',
    appId: '1:479021110175:web:7e2a3b12f23fa815ec23aa',
    messagingSenderId: '479021110175',
    projectId: 'quizzai-669e4',
    authDomain: 'quizzai-669e4.firebaseapp.com',
    storageBucket: 'quizzai-669e4.firebasestorage.app',
    measurementId: 'G-7KLGD20H9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-WIMhekG87MaTkxY_6pKdE4kBdNbPv5c',
    appId: '1:479021110175:android:188bc108f2b81417ec23aa',
    messagingSenderId: '479021110175',
    projectId: 'quizzai-669e4',
    storageBucket: 'quizzai-669e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXcHvbakHZv03dpIqYnk3kXxLUnAh6lCg',
    appId: '1:479021110175:ios:b9ddf7215bc1f710ec23aa',
    messagingSenderId: '479021110175',
    projectId: 'quizzai-669e4',
    storageBucket: 'quizzai-669e4.firebasestorage.app',
    iosBundleId: 'com.example.laptrinhdidong',
  );
}
